# Generated by Django 5.2 on 2025-04-17 23:20

import django.db.models.deletion
import registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.FileField(upload_to='treinamento/')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.SlugField(max_length=200, unique=True)),
                ('foto_facial', models.ImageField(upload_to='foto/')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=18, unique=True, validators=[registro.models.validar_cpf])),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('situacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColetaFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roi/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_coletas', to='registro.usuario')),
            ],
        ),
    ]
