# Generated by Django 5.2 on 2025-06-03 01:28

import django.db.models.deletion
from django.db import migrations, models


def set_usuario_for_treinamento(apps, schema_editor):
    Treinamento = apps.get_model('registro', 'Treinamento')
    Usuario = apps.get_model('registro', 'Usuario')

    usuario = Usuario.objects.first()
    if usuario is None:
        return  # Nenhum usuário cadastrado, nada a fazer

    for treino in Treinamento.objects.all():
        treino.usuario = usuario
        treino.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='usuario',
            field=models.OneToOneField(null=True, blank=True,on_delete=django.db.models.deletion.CASCADE, to='registro.usuario'),
        ),
        migrations.RunPython(set_usuario_for_treinamento),
        migrations.AlterField(
            model_name='treinamento',
            name='usuario',
            field=models.OneToOneField(null=False, on_delete=django.db.models.deletion.CASCADE, to='registro.usuario'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='modelo',
            field=models.FileField(blank=True, null=True, upload_to='treinamento/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.BooleanField(default=False),
        ),
        
    ]
