# Generated by Django 5.2 on 2025-06-06 12:50

import django.db.models.deletion
import registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_treinamento_embedding_treinamento_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coletafaces',
            name='image',
            field=models.ImageField(upload_to=registro.models.caminho_imagem_usuario),
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='registro.usuario')),
            ],
        ),
    ]
