# Generated by Django 5.2 on 2025-06-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_coletafaces_image_registroponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='data_treinamento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
